# Generated by Django 5.1.5 on 2025-01-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
