# Generated by Django 5.1.5 on 2025-01-30 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_test_title_test_message_test_repeat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_name', models.CharField(max_length=100)),
                ('robot_key', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='robot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.robot'),
        ),
    ]
