# Generated by Django 5.1.5 on 2025-02-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_robot_test_robot'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
