# Generated by Django 5.1.5 on 2025-02-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='timeframe',
            field=models.CharField(default='weekly', max_length=50),
        ),
    ]
